walk:
  - name: "amp"
    path: "walk/amp_pi_plus_20dof.yaml"
#   - name: "dreamwaq"
#     path: "walk/dreamwaq.yaml"
motion:
  # - name: "form1"
  #   path: "motion/form1.yaml"
  # - name: "form2"
  #   path: "motion/form2.yaml"
