walk:
  # - name: "lr"
  #   path: "walk/lr.yaml"
  # - name: "footstep"
  #   path: "walk/footstep.yaml"
motion:
  - name: "tpose"
    path: "motion/tpose.yaml"
#   # - name: "charles_dance"
#   #   path: "motion/charles_dance.yaml"
#   # - name: "lee"
#   #   path: "motion/lee.yaml"
#   - name: "form1"
#     path: "motion/form1.yaml"
#   - name: "form2"
#     path: "motion/form2.yaml"
#   # - name: "spin"
#   #   path: "motion/spin.yaml"
#   - name: "yongchun"
#     path: "motion/yongchun.yaml"
up:
  - name: "yangwo"
    # path: "up/yangwo.yaml"
    path: "up/fanyangwo.yaml"
  - name: "fuwo"
    path: "up/fuwo.yaml"
