float32 l_horizontal     # 左摇杆 水平方向
float32 l_vertical       # 左摇杆 垂直方向
float32 lt               # 左扳机键
float32 r_horizontal     # 右摇杆 水平方向
float32 r_vertical       # 右摇杆 垂直方向
float32 rt               # 右扳机键
float32 dpad_horizontal  # 十字键 水平方向
float32 dpad_vertical    # 十字键 垂直方向
float32 a                # a 
float32 b                # b
float32 x                # x
float32 y                # y
float32 lb               # 左肩键
float32 rb               # 右键键
float32 back             # back 中间键左侧
float32 start            # start 中间键右侧
float32 center           # 中间键
float32 L                # 左摇杆按下
float32 R                # 右摇杆按下
