# 人形机器人驱动器参数配置文件
# Humanoid Robot Driver Parameters Configuration

# 滤波参数
alpha: 0.6  # 一阶惯性滤波系数 (0.0-1.0)
            # 值越大响应越快，值越小越平滑
alpha_imu: 0.2  # 一阶惯性滤波系数 (0.0-1.0) 暂时该功能关闭
            # 值越大响应越慢
# 控制参数
control_frequency: 10.0    # 控制频率 (Hz)

# PD控制器参数 (IMU角度补偿)
pd_x:
  kp: 0.0   # X方向比例系数 (对应pitch角度补偿)
  kd: 0.0    # X方向微分系数 (对应pitch角度补偿)

pd_y:
  kp: 0.0     # Y方向比例系数 (对应roll角度补偿)
  kd: 0.0    # Y方向微分系数 (对应roll角度补偿)

# IMU配置
imu_topic: "/imu/data"     # IMU数据话题名称

# 本地发布配置
local_publish:
  enable: true                   # 是否启用本地发布
  topic: "/joy"                  # 本地发布话题名称

# 自旋自动前进配置
auto_forward:
  enable: false                  # 是否启用自旋自动前进功能
  speed: 0.18                    # 自动前进速度 
  rotation_threshold: 0.05       # 判断为旋转的最小阈值

