- production_type: "football"
  multi_waypoint_config:
    - name: "niuyao"
      key: "rt+a"
      remark: "扭腰"
    - name: "yizima"
      key: "rt+b"
      remark: "一字马"
    - name: "zhiliyaobai"
      key: "rt+x"
      remark: "直立腰摆"
    - name: "yatui"
      key: "rt+y"
      remark: "压腿"
    - name: "zuocewo"
      key: "null"
      remark: "跌倒爬起左侧卧"
    - name: "youcewo"
      key: "null"
      remark: "跌倒爬起右侧卧"
    - name: "yangwo"
      key: "null"
      remark: "跌倒爬起仰卧"
    - name: "fuwo"
      key: "null"
      remark: "跌倒爬起俯卧"
  series_waypoint_config:
  series_waypoint_config:
  policy_change_config:

- production_type: "Business performance"
  multi_waypoint_config:
    - name: "niuyao"
      key: "rt+a"
      remark: "扭腰"
    - name: "yizima"
      key: "rt+b"
      remark: "一字马"
    - name: "zhiliyaobai"
      key: "rt+x"
      remark: "直立腰摆"
    - name: "yatui"
      key: "rt+y"
      remark: "压腿"
    - name: "zuocewo"
      key: "null"
      remark: "跌倒爬起左侧卧"
    - name: "youcewo"
      key: "null"
      remark: "跌倒爬起右侧卧"
    - name: "yangwo"
      key: "null"
      remark: "跌倒爬起仰卧"
    - name: "fuwo"
      key: "null"
      remark: "跌倒爬起俯卧"
  series_waypoint_config:
  policy_change_config:
