walk:
  - name: "lr"
    path: "walk/lr.yaml"
  # - name: "footstep"
  #   path: "walk/footstep.yaml"
motion:
  # - name: "front_down"
  #   path: "motion/front_down.yaml"
  # - name: "front_up"
  #   path: "motion/front_up.yaml"
  # - name: "hand"
  #   path: "motion/hand.yaml"
  # - name: "charles_dance"
  #   path: "motion/charles_dance.yaml"
  # - name: "lee"
  #   path: "motion/lee.yaml"
  # - name: "form1"
  #   path: "motion/form1.yaml"
  # - name: "form2"
  #   path: "motion/form2.yaml"
  # - name: "spin"
  #   path: "motion/spin.yaml"
  # - name: "yongchun"
  #   path: "motion/yongchun.yaml"
  # - name: "yongchun_future"
  #   path: "motion/yongchun_future.yaml"
  # - name: "lie2yangwo_future"
  #   path: "motion/lie2yangwo_future.yaml"
  # - name: "lie2fuwo_future"
  #   path: "down/lie2fuwo_future.yaml"
  # - name: "yangwo"
  #   path: "up/yangwo.yaml"
  # - name: "fuwo"
  #   path: "up/fuwo.yaml"
  # - name: "charles_dance_future"
  #   path: "motion/charles_dance_future.yaml"
up:
  - name: "yangwo"
    # path: "up/yangwo.yaml"
    path: "up/fanyangwo.yaml"
  - name: "fuwo"
    path: "up/fuwo.yaml"
