name: "pi_plus_24dof"

dofs: 24

max_power: 200.0 # 最大功率限制
max_power_duration: 1.0 # 最大功率持续时间限制

joint_names: [
 "l_hip_pitch_joint", "l_hip_roll_joint", "l_thigh_joint", "l_calf_joint", "l_ankle_pitch_joint", "l_ankle_roll_joint", 
 "r_hip_pitch_joint", "r_hip_roll_joint", "r_thigh_joint", "r_calf_joint", "r_ankle_pitch_joint", "r_ankle_roll_joint",
 "l_shoulder_pitch_joint", "l_shoulder_roll_joint", "l_upper_arm_joint", "l_elbow_joint", "l_wrist_joint", 
 "r_shoulder_pitch_joint", "r_shoulder_roll_joint", "r_upper_arm_joint", "r_elbow_joint", "r_wrist_joint",
 "head_yaw_joint", "head_pitch_joint"]

map_index: [ 5,  4,  3,  2,  1,  0, 11, 10,  9,  8,  7,  6, 
            12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]

# 2.0.0机器人
direction: [1,  1, -1, -1,  1,  1, 
           -1,  1, -1,  1, -1,  1,
            1, -1, -1, -1,  1,
           -1, -1, -1,  1,  1,
            1,  1]

# 2.0.0 之前的机器人
# direction: [1,  1, -1, -1,  1,  1,
#            -1,  1, -1,  1, -1,  1,
#             1,  1, -1,  1,  1,
#            -1,  1, -1, -1,  1,
#             1,  1]

lower: [-3.14, -3.14, -3.14, -3.14, -3.14, -3.14,
        -3.14, -3.14, -3.14, -3.14, -3.14, -3.14,
        -3.14, -3.14, -3.50, -3.14, -3.14,
        -3.14, -3.14, -3.14, -3.14, -3.14,
        -1.57, -1.57]
upper: [ 3.14,  3.14,  3.14,  3.14,  3.14,  3.14,
         3.14,  3.14,  3.14,  3.14,  3.14,  3.14,
         3.14,  3.14,  3.14,  3.14,  3.14,
         3.14,  3.14,  3.14,  3.14,  3.14,
         1.57,  1.57]

kp: [110, 110, 110, 110, 210, 110,
     110, 110, 110, 110, 210, 110,
     60, 60, 60, 60, 60,
     60, 60, 60, 60, 60,
     60, 60]
kd: [1.1, 1.4, 1.1, 1.1, 1.1, 1.1,
     1.1, 1.4, 1.1, 1.1, 1.1, 1.1,
     0.3, 0.3, 0.3, 0.3, 0.3,
     0.3, 0.3, 0.3, 0.3, 0.3,
     0.3, 0.3]

urdf_offset: [ 0.00,  0.00,  0.00,  0.00,  0.00,  0.00,
               0.00,  0.00,  0.00,  0.00,  0.00,  0.00,
               # 2.1.1
               1.95, -1.57,  0.00, -1.57,
               1.95,  1.57,  0.00, -1.57,
               # 2.0.0
               # 1.95, -1.57,  1.57, -1.57,  0.00,
               # 1.95,  1.57, -1.57, -1.57,  0.00,
               # < 2.0.0
               # 1.95,  1.57,  1.57,  1.57, 0.00,
               # 1.95, -1.57, -1.57,  1.57, 0.00,
               0.00,  0.00]

waypoint_files: ["way_point/waypoint_lower_body.boost.bak", 
"way_point/waypoint_lower_body.boost.bak", 
"way_point/waypoint_lower_body.boost.bak", 
"way_point/waypoint_lower_body.boost.bak",  
"way_point/pi_plus_24dof_stand_up/waypoint_all_front_down.boost.bak",  
"way_point/pi_plus_24dof_stand_up/waypoint_all_back_down.boost.bak", 
"way_point/pi_plus_24dof_stand_up/waypoint_all_left_down.boost.bak", 
"way_point/pi_plus_24dof_stand_up/waypoint_all_right_down.boost.bak",
"way_point/hand.boost.bak"]

